### ISSUE TITLE
Add continuous deployment with Azure

### ISSUE THREAD

**Issue by KyleQ1** [KyleQ1/Its-just-flix-bro#60]
* Have azure deploy project
* Hide keys using Azure secrets
* Change DB password since it's exposed in commit history

**Comment by andrewtchan** [comment]
CD stuff pushed to main, deployment of backend and static frontend is working correctly on each push to main (showing site and backend routes that don't use Mongo are running). NOTE: ran into an unresolved Mongo/Azure connection bug near end of project, ran out of time to resolve.
